### PR TITLE
added feinberg.py

### PR DESCRIPTION
**Pull request by MarkFeinberg**

### CODE REVIEW

**Comment by MarkFeinberg** [comment]
@petrasovaa Hello. I tried fixing my file, feinberg.py, and all checks are passing except Render activities. Do you have any idea why this is not working? Thanks

**Comment by petrasovaa** [comment]
The CI didn't have numpy installed, which is needed for your code to run, so I added that.

**Comment by petrasovaa** [comment]
You changed the name of the variable, but you were supposed to change the raster name - the string.

**Comment by MarkFeinberg** [comment]
@petrasovaa everything worked. Thank you so much for all of your help!

**Review by petrasovaa — APPROVED** [review]

**Pull request merged**
