### PR TITLE
Add activity files

### PR DESCRIPTION
**Pull request by ocsmit**

### CODE REVIEW

**Review by petrasovaa — CHANGES_REQUESTED** [review]
Let me know if you end up needing an addon.

**Comment by ocsmit** [comment]
> Let me know if you end up needing an addon.

The update uses [r.accumulate](https://grass.osgeo.org/grass82/manuals/addons/r.accumulate.html). I included a try/catch for the case in which the addon is not installed

**Comment by petrasovaa** [comment]
I added the addon to CI, would you mind rebasing to main and see if the tests will run?

**Comment by ocsmit** [comment]
All passes checked! Thanks!

**Review by petrasovaa — APPROVED** [review]
The visualization could be improved, but let's call it done now.

**Pull request merged**
