### PR TITLE
add activity files Eli

### PR DESCRIPTION
**Pull request by EliHorner**

### CODE REVIEW

**Review by petrasovaa — CHANGES_REQUESTED** [review]
How about adding shadows? See https://grass.osgeo.org/grass82/manuals/r.sun.html#extraction-of-shadow-maps
Maybe you can derive the time as current time with python `datetime`.

**Comment by EliHorner** [comment]
Added derived current date

**Comment by petrasovaa** [comment]
> Added derived current date

That's good and now similarly add the shadows.

**Comment by EliHorner** [comment]
Added calculations accounting for shadows

**Comment by petrasovaa** [comment]
> Added calculations accounting for shadows

I don't think so, you need `incidout` option and specify time.

**Comment by petrasovaa** [comment]
> Fixed shadows (I think, not 100% sure I'm doing this right still)

Based on the documentation, you will need to add something like to show the shadow, and not the incidence angle:
```
gs.mapcalc("cast_shadow = if ( isnull(shadows), 1, null())", env=env)
```

and add the raster to the json for visualization.

**Comment by EliHorner** [comment]
Added mapcalc command and raster to json

**Comment by petrasovaa** [comment]
> Added mapcalc command and raster to json

It needs to right after r.sun call, not in the main function, so that it also gets executed in Tangible Landscape

**Review by petrasovaa — APPROVED** [review]

**Pull request merged**
